# Generated by Django 3.2.6 on 2021-08-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_comment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
