# Generated by Django 3.2.6 on 2021-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_alter_comment_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
